[package]
name = "unicode-ident-diagram"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
image = "0.24"
unicode-ident4c-ffi = { path = ".." }
